email:
  username: 3894507061@qq.com
  password: xmhauivhgeafcchb

mysql:
  ip: 192.168.150.128
  port: 3306
  username: root
  password: 24364726

redis:
  vector:
    host: 192.168.150.128
    port: 6379
    password: 24364726

chroma:
  base-url: http://192.168.150.128:8000
  collection-name: QAssistant
  timeout: 30

mongodb:
  ip: 192.168.150.128
  port: 27017
  database: QAssistant
  username: root
  password: 24364726

minio:
  url: http://192.168.150.128:9000
  accessKey: minio
  secretKey: bo@DwF1mzr_wF7am
  bucketName: 1115suc

langchain4j:
  open-ai:
    chat-model:
      model-name: Qwen/Qwen3.5-397B-A17B
      base-url: https://api.siliconflow.cn/v1
      api-key: sk-xgeiyazhpkjbdpijdmtnwnzgvblkqlxdccarwgqnfvmscdpa
      top-p: 1.0
      temperature: 0.7
      max-tokens: 4096
      timeout: 300s
      log-requests: true
      log-responses: true
    streaming-chat-model:
      model-name: Qwen/Qwen3.5-397B-A17B
      base-url: https://api.siliconflow.cn/v1
      api-key: sk-xgeiyazhpkjbdpijdmtnwnzgvblkqlxdccarwgqnfvmscdpa
      top-p: 1.0
      temperature: 0.7
      max-tokens: 4096
      timeout: 300s
      log-requests: true
      log-responses: true
    embedding-model:
      model-name: Qwen/Qwen3-Embedding-8B
      base-url: https://api.siliconflow.cn/v1
      api-key: sk-xgeiyazhpkjbdpijdmtnwnzgvblkqlxdccarwgqnfvmscdpa
      log-requests: true
      log-responses: true
